import { Phone, CodeIcon, PersonStanding } from "lucide-react";

export const Mock_Interviewers = [
  {
    id: 1,
    name: "Technical Interview",
    description: "Assesses coding, problem-solving, and CS fundamentals.",
    image: "technical-interview.jpg",
    icon: <CodeIcon size={48} />,
    src: "https://github.com/shadcn.png",
  },
  {
    id: 2,
    name: "Behavioral Interview",
    description: "Evaluates soft skills, teamwork, and past work experiences.",
    image: "behavioral-interview.jpg",
    icon: <PersonStanding size={48} />,
    src: "https://github.com/shadcn.png",
  },
  {
    id: 3,
    name: "Phone Interview",
    description: "Screens basic skills and communication before on-site.",
    image: "phone-interview.jpg",
    icon: <Phone size={48} />,
    src: "https://github.com/shadcn.png",
  },
  {
    id: 4,
    name: "Technical Focus Interviewer",
    description: "Deeply probes technical expertise in algorithms and design.",
    image: "phone-interview.jpg",
    icon: <Phone size={48} />,
    src: "https://github.com/shadcn.png",
  },
  {
    id: 5,
    name: "Friendly Interviewer",
    description: "Creates a relaxed space to showcase best abilities.",
    image: "phone-interview.jpg",
    icon: <Phone size={48} />,
    src: "https://github.com/shadcn.png",
  },
  {
    id: 6,
    name: "Aggressive Interviewer",
    description: "Tests problem-solving under pressure with hard questions.",
    image: "phone-interview.jpg",
    icon: <Phone size={48} />,
    src: "https://github.com/shadcn.png",
  },
  {
    id: 7,
    name: "Negative Interviewer",
    description: "Gauges resilience and handles difficult scenarios.",
    image: "phone-interview.jpg",
    icon: <Phone size={48} />,
    src: "https://github.com/shadcn.png",
  },
  {
    id: 8,
    name: "Helpful Interviewer",
    description: "Guides and hints to understand problem-solving process.",
    image: "phone-interview.jpg",
    icon: <Phone size={48} />,
    src: "https://github.com/shadcn.png",
  },
];